# Generated by Django 6.1.1 on 2026-09-20 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_bill_product_order_producttype_order_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='ist_paid',
            new_name='is_paid',
        ),
    ]
